import:
  - numpy as np

variables:
  x:
    dtype: np.ndarray
    description: the input vector

parameters:
  a:
    default: 20.0
    dtype: float
    description: the Ackley function 'a' parameter

  b:
    default: 0.2
    dtype: float
    description: the Ackley function 'b' parameter

  c:
    default: 2 * np.pi
    dtype: float
    description: the Ackley function 'c' parameter

  dim:
    default: 1
    dtype: int
    domain: v > 0
    description: the input vector dimension

description: |
  The Ackley function is a non-convex function used as a performance test problem for optimization algorithms.
  It was proposed by David Ackley in his 1987 PhD dissertation.

  It can be computed as 'f(x) = t1 + t2 - a - e', where:
      - t1 = a * e^{ -b * \sqrt {\sum_i {x_i ** 2} / d} }
      - t2 = e^{ \sum_i { \cos(c * x_i) / d } }
      - d is the dimensionality of the vector x
      - e is the euler number
      - a, b, c are three parameter, whose recommended values are a = 20, b = 0.2 and c = 2Ï€

  The function has its minimum in the vector 0_d.